services:
  configserver:
    image: "ngotruong764/configserver:s9"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "ngotruong764/eurekaserver:s9"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "ngotruong764/accounts:s9"
    container_name: accounts-ms
    ports:
      # Inside ports, we can define multiple post mapping
      # The - indicate an element of the array
      - "8082:8082"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config


  loans:
    image: "ngotruong764/loans:s9"
    container_name: loans-ms
    ports:
      - "8083:8083"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

#  loans1:
#    image: "ngotruong764/loans:s9"
#    container_name: loans1-ms
#    ports:
#      - "8085:8083"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    environment:
#      SPRING_APPLICATION_NAME: "loans"
#    extends:
#      file: common-config.yml
#      service: microservice-eurekaserver-config

  cards:
    image: "ngotruong764/cards:s9"
    container_name: cards-ms
    ports:
      - "8084:8084"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  gatewayserver:
    image: "ngotruong764/gatewayserver:s9"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

# Create a network with the name ngotruong764-network
# This network will be used to connect all the microservices
networks:
  ngotruong764-network:
    driver: "bridge"

