server:
  port: 9010

spring:
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        # This is an input binding
        emailsms-in-0:
          # Whenever we use input binding,
          # destination is considered as a queue
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s



  application:
    name: message

