server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ngotruong764/config-file.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

# If we need to encrypt the config repo
encrypt:
  key: JDIUEIO302NCFHU702NFB831OQWUJDIUEIO302NCFHU702NFB831OQWU

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"