server:
  port: 8082

spring:
  config:
    import: optional:configserver:http://localhost:8071/
  application:
    name: accounts
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # default name
    password: root # default password
  jpa:
    show-sql: true # Print all sql query
  sql:
    init:
      mode: always
# Spring doc property
springdoc:
  api-docs:
    path: /api-docs

# Enable actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'