spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/

# Enable actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: gatewayserver
    description: Gatewayserver Microservice
    version: 1.0.0

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG